# Generated by Django 2.1.7 on 2019-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_serial_number', models.CharField(max_length=254, unique=True, verbose_name='产品编号')),
                ('name', models.CharField(max_length=256, verbose_name='产品名称')),
                ('img', models.ImageField(blank=True, height_field=70, null=True, upload_to='products/', verbose_name='产品图片', width_field=70)),
                ('img_url', models.URLField(default='https://2d.zol-img.com.cn/product/190_80x60/227/ce8Ml2FxDOZE.jpg', max_length=254, verbose_name='产品图片链接')),
                ('series_id', models.IntegerField(verbose_name='所属系列')),
                ('feature_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='特性描述')),
                ('status', models.IntegerField(choices=[(0, '停售'), (1, '在售')], default=1, verbose_name='产品状态')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=20, unique=True, verbose_name='中文名称')),
                ('name_en', models.CharField(max_length=20, unique=True, verbose_name='英文名称')),
                ('site_link', models.CharField(max_length=254, unique=True, verbose_name='官网链接')),
                ('status', models.IntegerField(choices=[(0, '停售'), (1, '在售')], default=1, verbose_name='品牌状态')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'ordering': ['name_cn'],
            },
        ),
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_serial_number', models.CharField(max_length=254, unique=True, verbose_name='产品编号')),
                ('time_to_market', models.CharField(max_length=64, verbose_name='上市时间')),
                ('product_type', models.CharField(max_length=256, verbose_name='产品定位类型')),
                ('os_type', models.CharField(max_length=254, verbose_name='操作系统')),
                ('cpu_series', models.CharField(max_length=128, verbose_name='CPU系列')),
                ('cpu_type', models.CharField(max_length=128, verbose_name='CPU型号')),
                ('cpu_clock_speed', models.CharField(max_length=20, verbose_name='CPU主频')),
                ('cpu_turbo', models.CharField(max_length=20, verbose_name='CPU睿频')),
                ('core_num', models.CharField(max_length=50, verbose_name='核心数描述')),
                ('memory_cap', models.CharField(max_length=32, verbose_name='内存容量')),
                ('hd_type', models.CharField(max_length=128, verbose_name='硬盘类型')),
                ('hd_cap', models.CharField(max_length=128, verbose_name='硬盘容量')),
                ('graphics_type', models.CharField(max_length=64, verbose_name='显卡性能等级')),
                ('graphics_cap', models.CharField(max_length=32, verbose_name='显存容量')),
                ('sc_size', models.FloatField(max_length=20, verbose_name='屏幕尺寸')),
                ('screen_resolution', models.CharField(max_length=32, verbose_name='分辨率')),
                ('battery_type', models.CharField(max_length=128, verbose_name='电池类型')),
                ('life_time_intro', models.CharField(max_length=100, verbose_name='续航时间描述')),
                ('color', models.CharField(max_length=64, verbose_name='颜色')),
                ('weight', models.CharField(max_length=64, verbose_name='重量')),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.IntegerField(verbose_name='所属品牌')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='系列名称')),
                ('intro', models.CharField(blank=True, max_length=254, null=True, verbose_name='系列简介')),
                ('status', models.IntegerField(choices=[(0, '停售'), (1, '在售')], default=1, verbose_name='系列状态')),
            ],
            options={
                'verbose_name': '产品系列',
                'verbose_name_plural': '产品系列',
                'ordering': ['name'],
            },
        ),
    ]
