# Generated by Django 2.1.7 on 2019-05-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.IntegerField(default=1, verbose_name='所属品牌'),
            preserve_default=False,
        ),
    ]
