# Generated by Django 2.1.7 on 2019-05-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_brand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productconfiguration',
            name='sc_size',
            field=models.CharField(max_length=20, verbose_name='屏幕尺寸'),
        ),
    ]
