# Generated by Django 2.1.7 on 2019-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='所属用户')),
                ('fav_id', models.IntegerField(verbose_name='产品/商品id')),
                ('fav_type', models.IntegerField(choices=[(0, 'goods'), (1, 'products')], verbose_name='收藏类型')),
                ('price_when_fav', models.IntegerField(verbose_name='收藏时的售价')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加收藏时的时间')),
            ],
            options={
                'verbose_name': '用户收藏记录',
                'verbose_name_plural': '用户收藏记录',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='UserViewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='所属用户')),
                ('obj_id', models.IntegerField(verbose_name='商品/产品id')),
                ('obj_type', models.IntegerField(choices=[(0, 'goods'), (1, 'products')], verbose_name='类型')),
                ('view_time', models.DateTimeField(auto_now_add=True, verbose_name='查看时间')),
            ],
            options={
                'verbose_name': '用户浏览记录',
                'verbose_name_plural': '用户浏览记录',
                'ordering': ['user_id'],
            },
        ),
    ]
