# Generated by Django 2.1.7 on 2019-05-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='fav_id',
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='fav_prd_serial_number',
            field=models.CharField(max_length=200, verbose_name='产品编号'),
            preserve_default=False,
        ),
    ]
