# Generated by Django 2.1.7 on 2019-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(verbose_name='排名')),
                ('brand_id', models.IntegerField(verbose_name='对应的品牌')),
                ('composite_score', models.FloatField(verbose_name='综合评分')),
                ('brand_occupancy', models.FloatField(verbose_name='品牌占有率')),
                ('positive_rate', models.FloatField(verbose_name='好评率')),
                ('lowest_price', models.IntegerField(default=0, verbose_name='最低价')),
                ('highest_price', models.IntegerField(default=0, verbose_name='最高价')),
                ('product_num', models.IntegerField(default=0, verbose_name='产品数')),
                ('update_date', models.DateField(auto_now=True, verbose_name='信息更新时间')),
            ],
            options={
                'verbose_name': '品牌排行榜',
                'verbose_name_plural': '品牌排行榜',
                'ordering': ['ranking'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_serial_number', models.CharField(max_length=254, unique=True, verbose_name='产品编号')),
                ('fav_num', models.IntegerField(default=1, verbose_name='收藏次数')),
                ('update_date', models.DateField(auto_now=True, verbose_name='信息更新时间')),
            ],
            options={
                'verbose_name': '产品收藏次数统计',
                'verbose_name_plural': '产品收藏次数统计',
                'ordering': ['fav_num'],
            },
        ),
        migrations.CreateModel(
            name='PriceStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_serial_number', models.CharField(max_length=254, unique=True, verbose_name='产品编号')),
                ('official_price', models.IntegerField(default=0, verbose_name='官方报价')),
                ('lowest_price', models.IntegerField(default=0, verbose_name='最低售价')),
                ('highest_price', models.IntegerField(default=0, verbose_name='最高售价')),
                ('mall_num', models.IntegerField(default=0, verbose_name='在售商城数')),
                ('update_date', models.DateField(auto_now=True, verbose_name='信息更新时间')),
            ],
            options={
                'verbose_name': '产品售价信息统计',
                'verbose_name_plural': '产品售价信息统计',
                'ordering': ['prd_serial_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(verbose_name='排名')),
                ('prd_serial_number', models.CharField(max_length=254, unique=True, verbose_name='产品编号')),
                ('composite_score', models.FloatField(verbose_name='综合评分')),
                ('update_date', models.DateField(auto_now=True, verbose_name='信息更新时间')),
                ('ranking_type', models.IntegerField(choices=[(0, '热门笔记本电脑排行榜'), (1, '上升最快的笔记本电脑排行榜'), (2, '联想笔记本电脑排行榜'), (3, '戴尔笔记本电脑排行榜'), (4, 'ThinkPad笔记本电脑排行榜'), (5, '惠普笔记本电脑排行榜'), (6, '华为笔记本电脑排行榜'), (7, '苹果笔记本电脑排行榜'), (8, '华硕笔记本电脑排行榜'), (9, '雷神笔记本电脑排行榜'), (10, 'Alienware笔记本电脑排行榜'), (11, '游戏本排行榜'), (12, '商务办公本排行榜'), (13, '轻薄本排行榜'), (14, '超极本排行榜'), (15, '二合一笔记本排行榜'), (16, '校园学生本排行榜'), (17, '17英寸笔记本电脑排行榜'), (18, 'i9处理器笔记本排行榜'), (19, 'i7处理器笔记本排行榜'), (20, 'i5处理器笔记本排行榜'), (21, '发烧级显卡笔记本排行榜'), (22, '性能级显卡笔记本排行榜'), (23, '8G内存笔记本排行榜'), (24, '4G内存笔记本排行榜'), (25, '全高清笔记本排行榜'), (26, '固态硬盘笔记本排行榜'), (27, '混合硬盘笔记本排行榜'), (28, '3500-3999元笔记本排行榜'), (29, '4000-4999元笔记本排行榜'), (30, '5000-5999元笔记本排行榜'), (31, '6000-7999元笔记本排行榜'), (32, '8000元笔记本排行榜')], verbose_name='所属排行榜')),
            ],
            options={
                'verbose_name': '产品各类排行榜',
                'verbose_name_plural': '产品各类排行榜',
                'ordering': ['ranking_type'],
            },
        ),
        migrations.CreateModel(
            name='ViewStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_serial_number', models.CharField(max_length=254, unique=True, verbose_name='产品编号')),
                ('view_num', models.IntegerField(default=1, verbose_name='详情查看次数')),
                ('update_date', models.DateField(auto_now=True, verbose_name='信息更新时间')),
            ],
            options={
                'verbose_name': '产品详情查看次数统计',
                'verbose_name_plural': '产品详情查看次数统计',
                'ordering': ['view_num'],
            },
        ),
    ]
