# Generated by Django 2.1.7 on 2019-05-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStatistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritestatistics',
            name='user_ids',
            field=models.CharField(default='#', max_length=254, verbose_name='用户id字符串'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewstatistics',
            name='user_ids',
            field=models.CharField(default='#', max_length=254, verbose_name='用户id字符串'),
            preserve_default=False,
        ),
    ]
