# Generated by Django 2.1.7 on 2019-05-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStatistics', '0002_auto_20190522_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritestatistics',
            name='user_ids',
            field=models.CharField(max_length=1600, verbose_name='用户id字符串'),
        ),
        migrations.AlterField(
            model_name='viewstatistics',
            name='user_ids',
            field=models.CharField(max_length=1600, verbose_name='用户id字符串'),
        ),
    ]
